version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: build/Dockerfile
      target: dev
    container_name: golang_api_server
    stdin_open: true
    tty: true
    volumes:
      - ..:/go/src/app
    ports:
      - "8000:8000"
